const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.join(__dirname, "..");
const runScript = fs.readFileSync(path.join(root, "public", "agent-run.js"), "utf8");
const siteTheme = fs.readFileSync(path.join(root, "public", "local-site.css"), "utf8");

assert.match(runScript, /type="number" min="1" max="60" step="1"[^>]+data-replay-rate/);
assert.match(runScript, />FPS<\/span>/);
assert.doesNotMatch(runScript, /<select data-replay-rate/);
assert.match(runScript, /function updateReplayControlsInPlace\(container, viewId\)/);
assert.match(runScript, /function fitAsciiBoard\(\)/);
assert.match(runScript, /--run-ascii-font-size/);
assert.match(runScript, /function resolveReplayFrame\(turn\)/);
assert.match(runScript, /rendered view catching up/);
assert.doesNotMatch(runScript, /liveGrid\?\.classList\.toggle\("is-text-history"/);
assert.match(runScript, /document\.activeElement !== rateInput/);
assert.match(runScript, /playbackGeneration: 0/);
assert.match(runScript, /state\.playbackGeneration \+= 1/);
assert.match(runScript, /function isCurrentPlayback\(viewId, generation\)/);
assert.match(runScript, /playbackRequest && !isCurrentPlayback\(viewId, playbackGeneration\)/);
assert.match(runScript, /state\.playbackDeadline \+= replayDelay\(viewId\)/);
assert.match(runScript, /state\.playbackDeadline - performance\.now\(\)/);
assert.match(runScript, /control\.addEventListener\("input", \(event\) => updateRate\(event\)\)/);
assert.match(runScript, /data-replay-icon="play"/);
assert.match(runScript, /data-replay-icon="pause"/);
assert.doesNotMatch(runScript, /play\.innerHTML = playing/);
assert.match(runScript, /control\.addEventListener\("pointerdown"/);
assert.match(runScript, /control\.dataset\.replayPointerPending = "true"/);
assert.match(runScript, /delete control\.dataset\.replayPointerPending/);
assert.match(runScript, /event\.key !== "Enter" && event\.key !== " "/);
assert.match(runScript, /control\.dataset\.replayKeyboardPending = "true"/);
assert.match(runScript, /!pointerActivated && !keyboardActivated/);
assert.doesNotMatch(runScript, /replayPointerAt/);
assert.match(siteTheme, /\.replay-control__icon \{[\s\S]*?pointer-events: none/);
assert.match(siteTheme, /\.replay-control \{[\s\S]*?min-height: 40px/);
assert.match(siteTheme, /\.run-live__grid \{[\s\S]*?align-items: stretch/);
assert.match(siteTheme, /\.run-live__board \.agent-board \{[\s\S]*?height: 100%/);
assert.match(siteTheme, /\.run-live__json \.agent-board \{[\s\S]*?overflow: auto/);
assert.doesNotMatch(siteTheme, /\.run-live__grid\.is-text-history \.run-live__viewer/);
assert.match(siteTheme, /\.replay-rate input \{/);
assert.doesNotMatch(siteTheme, /\.replay-rate select \{/);

console.log("agent-run-playback-source: OK — playback has editable FPS and race-safe scheduling.");
