const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.join(__dirname, "..");
const pages = fs.readFileSync(path.join(root, "server", "pages.js"), "utf8");
const runService = fs.readFileSync(path.join(root, "server", "agent-runs.js"), "utf8");
const runScript = fs.readFileSync(path.join(root, "public", "agent-run.js"), "utf8");
const siteTheme = fs.readFileSync(path.join(root, "public", "local-site.css"), "utf8");

assert.match(pages, /id="run-heatmap-canvas"[^>]+aria-label="Player visit heatmap across the explored world"/);
assert.match(pages, /<h3 class="run-board-state-chart__title">Novelty rate<\/h3>/);
assert.match(pages, /id="run-board-state-basis"[\s\S]*?Board state[\s\S]*?Player world position/);
assert.match(pages, /id="run-board-state-scope"[\s\S]*?Cumulative[\s\S]*?Last 100 moves[\s\S]*?Last N moves/);
assert.match(pages, /class="run-board-state-chart__controls"[\s\S]*?id="run-board-state-basis"[\s\S]*?id="run-board-state-scope"[\s\S]*?id="run-board-state-chart"/);
assert.match(pages, /id="run-board-state-window"[^>]+min="1"[^>]+max="10000"[^>]+value="100"/);
assert.match(pages, /id="run-board-state-chart"[\s\S]*?<div class="run-heatmap__head">[\s\S]*?<h2>Heatmap<\/h2>[\s\S]*?id="run-heatmap-viewport"/);
assert.match(pages, /Less visited[\s\S]*Most visited/);
assert.doesNotMatch(pages, /Player visits by x\/y position\. Elevation is combined\./);
assert.match(pages, /id="run-heatmap-export-format"[\s\S]*?<option value="gif">GIF<\/option>[\s\S]*?<option value="mp4">MP4<\/option>/);
assert.match(pages, /id="run-heatmap-export"[^>]+>Export GIF<\/button>/);
assert.equal((pages.match(/\$\{heatmapSection\}/g) || []).length, 2);
assert.match(pages, /\$\{explorationSection\}[\s\S]*?\$\{heatmapSection\}[\s\S]*?\$\{movesSection\}/);
assert.match(runService, /const players = new Map\(\)/);
assert.match(runService, /const player = normalizedPlayerPosition\(response\?\.player\)/);
assert.match(runService, /initial_player: initialPlayer/);
assert.match(runService, /action\.player \|\|= reconstructed\.players\.get\(Number\(action\.turn\)\) \|\| null/);
assert.match(runService, /initial_board_state_hash: initialBoardStateHash \|\| null/);
assert.match(runService, /board_state_hash: record\.status\?\.board_state_hash \|\| null/);
assert.match(runService, /board_state_hash_version: Number\(record\.status\?\.board_state_hash_version\) \|\| null/);
assert.match(runService, /legacyBoardStateHashes/);
assert.match(runService, /evaluationActions = actions\.map/);
assert.match(runScript, /const BOARD_STATE_NOVELTY_WINDOW = 100/);
assert.match(runScript, /boardStateMetricMode: "last-100"/);
assert.match(runScript, /function boardStateMetricSettings\(\)/);
assert.match(runScript, /function playerWorldPositionKey\(player, roomValue\)/);
assert.match(runScript, /columnIndex \* 16 \+ position\.x/);
assert.match(runScript, /rowIndex \* 16 \+ position\.y/);
assert.match(runScript, /function boardStateNoveltyPoints\(\)/);
assert.match(runScript, /function isCameraRotationCommand\(value\)/);
assert.match(runScript, /if \(isCameraRotationCommand\(move\.action\)\) return/);
assert.match(runScript, /seen\.add\(initialKey\)/);
assert.match(runScript, /cumulativeNovel \/ cumulativeTotal \* 100/);
assert.match(runScript, /novelInWindow \/ windowSize \* 100/);
assert.match(runScript, /boardStateScope\?\.addEventListener\("change"/);
assert.match(runScript, /boardStateBasis\?\.addEventListener\("change"/);
assert.match(runScript, /boardStateWindowInput\?\.addEventListener\("input"/);
assert.match(runScript, /function drawBoardStateChart\(\)/);
assert.match(runScript, /function moveAxisLabels\(firstAction, lastAction\)/);
assert.equal((runScript.match(/moveAxisLabels\(/g) || []).length, 4);
assert.match(runScript, /Math\.ceil\(firstAction \/ 100\) \* 100/);
const moveAxisLabelsSource = runScript.match(/function moveAxisLabels\(firstAction, lastAction\) \{[\s\S]*?\n  \}/)?.[0];
assert.ok(moveAxisLabelsSource);
const moveAxisLabels = Function(`${moveAxisLabelsSource}; return moveAxisLabels;`)();
assert.deepEqual(moveAxisLabels(1, 385), [100, 200, 300, 385]);
assert.deepEqual(moveAxisLabels(1, 400), [100, 200, 300, 400]);
assert.deepEqual(moveAxisLabels(1, 65), [65]);
assert.match(runScript, /fillText\("Moves"/);
assert.match(runScript, /fillText\("Board-state novelty"/);
assert.doesNotMatch(runScript, /target\.duplicate \? "#ff9d52"/);
assert.doesNotMatch(pages, /camera angle excluded/);
assert.doesNotMatch(runScript, /Globally new \$\{subject\} among the latest/);
assert.match(runScript, /if \(!roomVisits\.has\(room\)\) roomVisits\.set\(room, new Map\(\)\)/);
assert.match(runScript, /state\.moves\.forEach\(\(move\) => add\(move\.player, move\.roomId \|\| move\.room\)\)/);
assert.match(runScript, /const roomSize = 16/);
assert.match(runScript, /room\.columnIndex \* roomSize \+ x/);
assert.match(runScript, /room\.rowIndex \* roomSize \+ y/);
assert.match(runScript, /columns: \(maxRoomColumn - minRoomColumn \+ 1\) \* roomSize/);
assert.match(runScript, /rows: \(maxRoomRow - minRoomRow \+ 1\) \* roomSize/);
assert.match(runScript, /each room is 16 by 16 cells and positioned on the world map/);
assert.match(runScript, /column - data\.minRoomColumn\) \* data\.roomSize \* cellWidth/);
assert.match(runScript, /row - data\.minRoomRow\) \* data\.roomSize \* cellHeight/);
assert.match(runScript, /Math\.log1p\(count\)/);
assert.match(runScript, /data\.uniqueCells \/ data\.totalVisits \* 100/);
assert.match(runScript, /\["cells", "Cells visited"\]/);
assert.match(runScript, /\["visits", "Total visits"\]/);
assert.match(runScript, /\["new-rate", "New-cell visits"\]/);
assert.match(runScript, /function heatmapVisitSequence\(data\)/);
assert.match(runScript, /const durationSeconds = 16/);
assert.match(runScript, /const fps = 25/);
assert.match(runScript, /gifWriteText\(bytes, "GIF89a"\)/);
assert.match(runScript, /function gifLzwEncode\(indices, minimumCodeSize\)/);
assert.ok((runScript.match(/\[0, 0, 0\]/g) || []).length >= 2);
assert.match(runScript, /downloadHeatmapExport\(blob, "gif"\)/);
assert.match(runScript, /function exportHeatmapMp4\(\)/);
assert.match(runScript, /new MediaRecorder\(stream, \{ mimeType, videoBitsPerSecond: 320_000 \}\)/);
assert.match(runScript, /context\.fillStyle = "#000";[\s\S]*context\.fillRect\(0, 0, canvas\.width, canvas\.height\)/);
assert.match(runScript, /context\.strokeStyle = "#242424"/);
assert.match(runScript, /downloadHeatmapExport\(blob, "mp4"\)/);
assert.match(runScript, /\[0, \[255, 216, 77\]\]/);
assert.match(runScript, /\[1, \[139, 76, 220\]\]/);
assert.match(runScript, /elevation combined/);
assert.match(siteTheme, /linear-gradient\(90deg, #ffd84d 0%, #ff972d 34%, #ef3e54 67%, #8b4cdc 100%\)/);
assert.match(siteTheme, /\.run-heatmap__summary \{[\s\S]*border-radius: 999px/);
assert.match(siteTheme, /\.run-heatmap__format \{[\s\S]*?width: auto;/);
assert.match(siteTheme, /\.run-heatmap__export \{[\s\S]*?white-space: nowrap;/);
assert.match(siteTheme, /\.run-board-state-chart \{[\s\S]*?margin-bottom: 18px/);
assert.match(siteTheme, /\.run-board-state-chart__controls \{[\s\S]*?margin-bottom: 10px/);
assert.match(siteTheme, /\.run-board-state-chart__scope \{[\s\S]*?height: 32px;[\s\S]*?width: auto;/);
assert.match(siteTheme, /#run-board-state-basis \{[\s\S]*?min-width: 184px/);
assert.match(siteTheme, /\.run-board-state-chart__custom-window input \{[\s\S]*?min-height: 22px/);

console.log("agent-run-heatmap-source: OK — 16×16 rooms share one world-positioned heatmap and elevation is ignored.");
