const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.join(__dirname, "..");
const appSource = fs.readFileSync(path.join(root, "server", "app.js"), "utf8");
const buildScript = fs.readFileSync(path.join(root, "public", "build.js"), "utf8");
const buildTheme = fs.readFileSync(path.join(root, "public", "build-theme.css"), "utf8");
const pageChrome = fs.readFileSync(path.join(root, "server", "page-chrome.js"), "utf8");
const pages = fs.readFileSync(path.join(root, "server", "pages.js"), "utf8");
const playCore = fs.readFileSync(path.join(root, "public", "play-core.js"), "utf8");
const playRenderer = fs.readFileSync(path.join(root, "public", "play-render-three.js"), "utf8");
const playScript = fs.readFileSync(path.join(root, "public", "play.js"), "utf8");
const playTheme = fs.readFileSync(path.join(root, "public", "play-theme.css"), "utf8");
const router = fs.readFileSync(path.join(root, "server", "router.js"), "utf8");

assert.match(buildScript, /world-card new-world-card/);
assert.match(buildScript, /world-card world-card--draft/);
assert.match(buildScript, /badge badge--updated/);
assert.match(buildScript, /card-actions card-actions--draft/);
assert.match(buildScript, /class="world-card__link" href="\$\{escapeText\(world\.author_url\)\}"/);
assert.match(buildScript, />Edit<\/a>/);
assert.match(buildScript, />Play<\/a>/);
assert.match(buildScript, />Delete<\/button>/);
assert.doesNotMatch(buildScript, />Publish<\/button>/);
assert.match(buildTheme, /\.new-world-card__plus/);
assert.match(buildTheme, /\.world-card--draft \.card-body/);
assert.match(buildTheme, /\.world-card--draft \.card-actions/);
assert.match(buildTheme, /\.build-modal\.open/);
assert.match(pages, /Build and Play/);
assert.doesNotMatch(pages, /modeCard\("\/play"/);
assert.match(pages, /\["Edit", `\/author\/maze\//);
assert.doesNotMatch(pages, /\["Edit Levels", `\/author\/maze\//);
assert.doesNotMatch(pageChrome, /href="\/play">Play<\/a>/);
assert.match(pageChrome, /<span class="brand-mark"[^>]*>\$\{BRAND_MARK_SVG\}<\/span>Maze Bench/);
assert.match(playTheme, /\.wm \{ fill: #ffd15c; stroke: #ffd15c; stroke-width: 1\.5; \}/);
assert.doesNotMatch(playTheme, /mbChromL|mbChromR|mbWrtick|mbWbtick/);
assert.match(playTheme, /translate: 0 calc\(-1 \* var\(--mb-logo-lift, 0px\)\)/);
assert.doesNotMatch(playTheme, /--mb-sign-gap|--mb-scene-h/);
assert.doesNotMatch(playTheme, /wordmark-m/);
assert.match(router, /if \(url\.pathname === "\/play"\) \{[\s\S]*?sendRedirect\(response, "\/build"\)/);

assert.match(pages, /window\.__PLAY_WORLD_DATA__/);
assert.match(pages, /maze-frame is-loading/);
assert.match(pages, /class="maze-load-label">Loading</);
assert.match(pages, /maze-load-progress/);
assert.match(playScript, /renderer\.primeHomeEdgeReveal/);
assert.match(playScript, /renderer\.beginHomeEdgeReveal/);
assert.match(playScript, /function diveIntoRoom/);
assert.match(playScript, /playData\.hostFullBleedView = true/);
assert.match(pages, /class="mazebench-controls"/);
assert.match(pages, /data-quadrant-pad="move"/);
assert.match(pages, /data-quadrant-pad="camera"/);
assert.match(playScript, /const sourceWidth = Math\.max\(1, Number\(app\.boardRect\?\.width\) \/ renderScale \|\| roomWidth\)/);
assert.doesNotMatch(playScript, /function playWorldFitOptions/);
assert.match(playRenderer, /app\.worldViewVistaMode !== true/);
assert.match(playRenderer, /app\.homeVectorTheme !== true/);
assert.match(playRenderer, /const zoomDistanceFactor = Math\.max\(/);
assert.match(playRenderer, /4 \*\s*zoomDistanceFactor/);
assert.match(playScript, /app\.homeVectorTheme = true/);
assert.match(playScript, /app\.vectorGlowAmount = 1/);
assert.match(pages, /data-action="world-map" aria-controls="world-map-overlay"/);
assert.match(pages, /id="world-map-overlay" class="world-map-overlay"/);
assert.match(pages, /id="world-map-grid" class="world-map-grid"/);
assert.match(pages, /play-theme\.css\?v=\$\{PLAY_ASSET_VERSION\}/);
assert.match(pages, /play\.js\?v=\$\{PLAY_ASSET_VERSION\}/);
assert.match(appSource, /STATIC_CACHE_CONTROL = "no-cache, max-age=0, must-revalidate"/);
assert.match(playScript, /function renderPlayWorldMap\(\)/);
assert.match(playScript, /async function switchPlayWorldLevel\(levelId\)/);
assert.match(playCore, /hostOwnsWorldMapNavigation: playData\?\.hostOwnsWorldMapNavigation === true/);
assert.match(playCore, /autoUndoPlayerFalls: playData\?\.autoUndoPlayerFalls === true/);
assert.match(playCore, /new window\.CustomEvent\("mazebench:level-state-applied"/);
assert.match(playScript, /if \(app\.hostOwnsWorldMapNavigation === true\) return;/);
assert.match(playScript, /function playWorldMapTransitionSnapshot\(\)/);
assert.match(playScript, /const roomDistance = Math\.hypot\(dx, dy\)/);
assert.match(playScript, /prewarmAdjacentLevelTransition\?\.\(transitionData, durationMs\)/);
assert.match(playScript, /startLevelTransition\(null, null, dx, dy/);
assert.match(playTheme, /#world-map-overlay \.world-map-grid \{[\s\S]*?grid-auto-rows: var\(--world-map-tile-size/);
assert.match(playTheme, /#game-root \.maze-load-label \{/);
assert.match(playTheme, /font-size: clamp\(16px, 1\.8vw, 22px\)/);
assert.ok(
  playScript.indexOf("let worldMapSwitching = false;") < playScript.indexOf("installPlayControls();"),
  "Play overlay state must initialize before controls synchronize it"
);
assert.match(playScript, /const cameraYawDurationMs = 400/);
assert.match(playScript, /skipRender: true/);
assert.match(playScript, /skipResize: true/);
assert.match(playScript, /preserveSceneCache: true/);
assert.match(playScript, /\(now, "camera"\)/);
assert.match(playCore, /renderedFrameChannels/);
assert.match(playCore, /renderOncePerFrame\(now = performance\.now\(\), channel = "scene"\)/);
assert.match(playRenderer, /fitCameraToScene\(cameraFlightFitOptions\(\) \|\| \{\}\)/);
assert.match(playScript, /const moveRepeatIntervalMs = 100/);
assert.match(playScript, /function quadrantPadButtonAtPoint\(pad, clientX, clientY\)/);
assert.match(playScript, /Math\.hypot\(dx, dy\) > radius/);
assert.match(playScript, /Math\.abs\(dx\) > Math\.abs\(dy\)/);
assert.match(playTheme, /\.control-pad\[data-quadrant-pad\] \{[\s\S]*?pointer-events: auto/);
assert.doesNotMatch(playTheme, /clip-path: circle/);
assert.match(playScript, /Math\.min\(rect\.width, rect\.height\) \* 0\.56/);
assert.match(playScript, /app\.cancelQueuedAction\?\.\(inputSource\)/);
assert.match(playScript, /playData\.autoUndoPlayerFalls = true/);
assert.match(playScript, /const cameraTiltAcceleration = Math\.PI \* 3\.4/);
assert.match(playScript, /enableCameraControls: false/);
assert.doesNotMatch(playScript, /new KeyboardEvent/);

console.log("site-parity-source: OK — MazeJam cards and blue-edge opening motion are canonical locally.");
